### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TurtleWolfe** [jfox015/Bonfire-News#20]
The installation process states I may be asked if I want it to overwrite some files... It's not doing this. Everything is in a BonfireNews directory. I move the News directory into my Modules folder and then seem able to migrate, but alot of the core components are still not in place. Any advice would be appreciated. This module sounds very promising!

**Comment by jfox015** [comment]
@TurtleWolf This refers mostly to existing directories when you extract this into your bonfire install. More the most part, the files themselves should all be unique. This module is currently only compatible with 0.6.1 and I know the directory structure was changed in 0.7 so that may be part of the core files issue. I'm going to close this in favor of a 0.7 update which may solve these issues. For now, be sure to run this with 0.6.1.
